### ISSUE TITLE
Updates per GRASS 7 native LiDAR support

### ISSUE THREAD

**Issue by dnix** [pmlrsg/arsf_dem_scripts#5]
Any chance there are any updates to this library for GRASS 7? Particularly with native las/laz support now. Thank you!

**Comment by danclewley** [comment]
With the latest commits the library should now work with GRASS7. We would like to add support for reading LAS files using `r.in.lidar` at some point but don't have a timeframe for this at the moment.

**Comment by dnix** [comment]
Awesome -- thanks a million. Considering taking a stab at adding the support for `r.in.lidar` and `v.in.lidar` myself. If I do get around to it eventually, I'll be sure to submit a PR to the dev branch
